'use strict';

(function (window) {
    window.regionsHelper = {
        drawCities: function(map) {
            map.drawCity("Россия, республика Адыгея");
            map.drawCity("Россия, республика Алтай");
            map.drawCity("Россия, Алтайский край");
            map.drawCity("Россия, Амурская область");
            map.drawCity("Россия, Архангельская область");
            map.drawCity("Россия, Астраханская область");
//					map.drawCity("Байконур г");
            map.drawCity("Россия, республика Башкортостан");
            map.drawCity("Россия, Белгородская область");
            map.drawCity("Россия, Брянская область");
            map.drawCity("Россия, республика Бурятия");
            map.drawCity("Россия, Владимирская область");
            map.drawCity("Россия, Волгоградская область");
            map.drawCity("Россия, Вологодская область");
            map.drawCity("Россия, Воронежская область");
            map.drawCity("Россия, республика Дагестан");
            map.drawCity("Россия, Еврейская Аобл");
            map.drawCity("Россия, Забайкальский край");
            map.drawCity("Россия, Ивановская область");
            map.drawCity("Россия, республика Ингушетия");
            map.drawCity("Россия, Иркутская область");
            map.drawCity("Россия, республика Кабардино-Балкарская");
            map.drawCity("Россия, Калининградская область");
            map.drawCity("Россия, республика Калмыкия");
            map.drawCity("Россия, Калужская область");
            map.drawCity("Россия, Камчатский край");
            map.drawCity("Россия, республика Карачаево-Черкесская");
            map.drawCity("Россия, республика Карелия");
            map.drawCity("Россия, Кемеровская область");
            map.drawCity("Россия, Кировская область");
            map.drawCity("Россия, республика Коми");
            map.drawCity("Россия, Костромская область");
            map.drawCity("Россия, Краснодарский край");
            map.drawCity("Россия, Красноярский край");
            map.drawCity("Россия, республика Крым");
            map.drawCity("Россия, Курганская область");
            map.drawCity("Россия, Курская область");
            map.drawCity("Россия, Ленинградская область");
            map.drawCity("Россия, Липецкая область");
            map.drawCity("Россия, Магаданская область");
            map.drawCity("Россия, республика Марий Эл");
            map.drawCity("Россия, республика Мордовия");
            map.drawCity("Россия, Мурманская область");
            map.drawCity("Россия, Ненецкий АО");
            map.drawCity("Россия, Нижегородская область");
            map.drawCity("Россия, Новгородская область");
            map.drawCity("Россия, Новосибирская область");
            map.drawCity("Россия, Омская область");
            map.drawCity("Россия, Оренбургская область");
            map.drawCity("Россия, Орловская область");
            map.drawCity("Россия, Пензенская область");
            map.drawCity("Россия, Пермский край");
            map.drawCity("Россия, Приморский край");
            map.drawCity("Россия, Псковская область");
            map.drawCity("Россия, Ростовская область");
            map.drawCity("Россия, Рязанская область");
            map.drawCity("Россия, Самарская область");
            map.drawCity("Россия, Саратовская область");
            map.drawCity("Россия, республика Саха /Якутия/");
            map.drawCity("Россия, Сахалинская область");
            map.drawCity("Россия, Свердловская область");
//					map.drawCity("Россия, Севастополь г");
            map.drawCity("Россия, республика Северная Осетия - Алания");
            map.drawCity("Россия, Смоленская область");
            map.drawCity("Россия, Ставропольский край");
            map.drawCity("Россия, Тамбовская область");
            map.drawCity("Россия, республика Татарстан");
            map.drawCity("Россия, Тверская область");
            map.drawCity("Россия, Томская область");
            map.drawCity("Россия, Тульская область");
            map.drawCity("Россия, республика Тыва");
            map.drawCity("Россия, Тюменская область");
            map.drawCity("Россия, республика Удмуртская");
            map.drawCity("Россия, Ульяновская область");
            map.drawCity("Россия, Хабаровский край");
            map.drawCity("Россия, республика Хакасия");
            map.drawCity("Россия, Ханты-Мансийский Автономный округ - Югра Автономный округ");
            map.drawCity("Россия, Челябинская область");
            map.drawCity("Россия, Чеченская республика ");
            map.drawCity("Россия, республика Чувашия");
            map.drawCity("Россия, Чукотский Автономный округ");
            map.drawCity("Россия, Ямало-Ненецкий Автономный округ");
            map.drawCity("Россия, Ярославская область");
        }
        , drawCitiesSamara: function(map) {
            map.drawCity("Самарская область, Самара");
            map.drawCity("Самарская область, Тольятти");
            map.drawCity("Самарская область, Похвистнево");
            map.drawCity("Самарская область, Отрадный");
            map.drawCity("Самарская область, Кинель-Черкассы");
            map.drawCity("Самарская область, Суходол");
            map.drawCity("Самарская область, Нефтегорск");
            map.drawCity("Москва");
            map.drawCity("Московская область");
            map.drawCity("Московская область, Королев");
            map.drawCity("Московская область, Одинцово");
            map.drawCity("Санкт-Петербург");
            map.drawCity("Екатеринбург");
            map.drawCity("Чита");
            map.drawCity("Абаза");
            map.drawCity("Абдулино");
        }
        , drawCitiesCentral: function(map) {
            var highlightRegion= function highlightRegion(e, feature) {
                globals.mapInfoControl.detail(feature.properties.regionName);
//                console.log('highlightRegion: '+feature.properties.regionName);
                return false;
            };

//			map.drawCity("Россия, Центральный федеральный округ", {}, highlightRegion);
//            map.drawCity("Россия, Белгородская область", {}, highlightRegion);
            map.drawCity("Россия, Брянская область", {}, highlightRegion);
            map.drawCity("Россия, Владимирская область", {}, highlightRegion);
//            map.drawCity("Россия, Воронежская область", {}, highlightRegion);
            map.drawCity("Россия, Ивановская область", {}, highlightRegion);
            map.drawCity("Россия, Калужская область", {}, highlightRegion);
            map.drawCity("Россия, Костромская область", {}, highlightRegion);
//            map.drawCity("Россия, Курская область", {}, highlightRegion);
//            map.drawCity("Россия, Липецкая область", {}, highlightRegion);
            map.drawCity("Россия, Москва", {}, highlightRegion);
            map.drawCity("Россия, Московская область", {}, highlightRegion);
//            map.drawCity("Россия, Орловская область", {}, highlightRegion);
            map.drawCity("Россия, Рязанская область", {}, highlightRegion);
            map.drawCity("Россия, Смоленская область", {}, highlightRegion);
            map.drawCity("Россия, Тверская область", {}, highlightRegion);
//            map.drawCity("Россия, Тульская область", {}, highlightRegion);
//            map.drawCity("Россия, Тамбовская область", {}, highlightRegion);
            map.drawCity("Россия, Ярославская область", {}, highlightRegion);
        }
    };
})(window);
